### PR TITLE
Removed absolute paths

### PR DESCRIPTION
**Pull request by manujuniris**
This PR removes all the absolute paths.

### CODE REVIEW

**Comment by redDwarf03** [comment]
Logo are not the good one. You took an old one
Capture d’écran 2022-08-30 à 10 20 20
Go to https://medium.com/ to take the good one

**Comment by redDwarf03** [comment]
Why do you use target="_blank for some links like Foundation, Brand Assets, .. but not for yellow paper or white paper

**Comment by manujuniris** [comment]
> Logo are not the good one. You took an old one Capture d’écran 2022-08-30 à 10 20 20 Go to https://medium.com/ to take the good one

I have added the latest icon for medium

**Comment by redDwarf03** [comment]
- Warning, the uco button is over the link
Capture d’écran 2022-09-02 à 22 44 31

- Remove in index.html these lines. There are not necessary 
```
  <link rel="canonical" href="/" />
    <link rel='shortlink' href='/' />
```

- Could you align vertically the medium logo please
Capture d’écran 2022-09-02 à 22 48 48

**Pull request merged**
